server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: auth_process
      password: auth_process

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true
