server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URI}
          predicates:
            - Path=/users/**

        - id: auth-service
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/auth/**
  security:
    oauth2:
      resource-server:
        jwt:
          public-key-location: file:${PUBLIC_KEY_PATH}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true