server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCES_URL}
    username: ${SPRING_DATASOURCES_USERNAME}
    password: ${SPRING_DATASOURCES_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true
